package com.spay.model.merchant;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


@Entity
@Table(name="merchant")
public class Merchant {
	
	
	private static final long serialVersionUID = 1L;

	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="merchant_Seq")
    @SequenceGenerator(name="merchant_Seq", sequenceName="merchant_Seq", allocationSize=1)
	@Column(name = "ID")
	private long Id;
	
	
	@Column(name="merchant_Id")
	private String merchantId;
	
	
	@Column(name="email_Id")
	private String emailId;
	
	
	@Column(name="merchant_name")
	private String merchantName;
	
	
	@Column(name="merchant_ref_no")
	private String merchant_ref_no;
	
	
	@Column(name="telephone")
	private long telephone;
	
	
	@Column(name="region")
	private String region;
	
	
	@Column(name="merchant_category_code")
	private String mcccode;
	
	
	@Column(name="autogenerated_password")
	private String autogeneratedPassword;
	
	
	@Column(name="changed_password")
	private String changedPassword;
	
	
	@Column(name="is_active")
	private boolean active;
	
	@Column(name="startdate")
	private String startdate;
	
	@Column(name="enddate")
	private String enddate;

	@Column(name="mobile")
	private long mobile;
	
	@Column(name="business")
	private String business;
	
	@Column(name="membership_type")
	private String membershiptype;
	
	@Column(name="address")
	private String address;
	
	@Column(name="transaction_fee")
	private long transactionfee;
	
	@Column(name="country")
	private String country;
	
	@Column(name="DOB")
	private Date DOB;
	
	@Column(name="product_form")
	private String productform;
	
	@Column(name="fees_setting")
	private String feessetting;
	
	/**
	 * @return the dOB
	 */
	public Date getDOB() {
		return DOB;
	}

	/**
	 * @param dOB the dOB to set
	 */
	public void setDOB(Date dOB) {
		DOB = dOB;
	}

	public String getMerchantId() {
		return merchantId;
	}

	public void setMerchantId(String merchantId) {
		this.merchantId = merchantId;
	}

	public String getEmailId() {
		return emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public String getMerchantName() {
		return merchantName;
	}

	public void setMerchantName(String merchantName) {
		this.merchantName = merchantName;
	}

	public String getMerchant_ref_no() {
		return merchant_ref_no;
	}

	public void setMerchant_ref_no(String merchant_ref_no) {
		this.merchant_ref_no = merchant_ref_no;
	}


	public String getRegion() {
		return region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getMcccode() {
		return mcccode;
	}

	public void setMcccode(String mcccode) {
		this.mcccode = mcccode;
	}

	public String getAutogeneratedPassword() {
		return autogeneratedPassword;
	}

	public void setAutogeneratedPassword(String autogeneratedPassword) {
		this.autogeneratedPassword = autogeneratedPassword;
	}

	public String getChangedPassword() {
		return changedPassword;
	}

	public void setChangedPassword(String changedPassword) {
		this.changedPassword = changedPassword;
	}

	public boolean isActive() {
		return active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}
	public boolean getActive() {
		return active;
	}

	public String getStartdate() {
		return startdate;
	}

	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}

	public String getEnddate() {
		return enddate;
	}

	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	/**
	 * @return the id
	 */
	public long getId() {
		return Id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(long id) {
		Id = id;
	}

	/**
	 * @return the telephone
	 */
	public long getTelephone() {
		return telephone;
	}

	/**
	 * @param telephone the telephone to set
	 */
	public void setTelephone(long telephone) {
		this.telephone = telephone;
	}

	/**
	 * @return the mobile
	 */
	public long getMobile() {
		return mobile;
	}

	/**
	 * @param mobile the mobile to set
	 */
	public void setMobile(long mobile) {
		this.mobile = mobile;
	}

	/**
	 * @return the business
	 */
	public String getBusiness() {
		return business;
	}

	/**
	 * @param business the business to set
	 */
	public void setBusiness(String business) {
		this.business = business;
	}

	/**
	 * @return the membershiptype
	 */
	public String getMembershiptype() {
		return membershiptype;
	}

	/**
	 * @param membershiptype the membershiptype to set
	 */
	public void setMembershiptype(String membershiptype) {
		this.membershiptype = membershiptype;
	}

	/**
	 * @return the address
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * @param address the address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	

	/**
	 * @return the transactionfee
	 */
	public long getTransactionfee() {
		return transactionfee;
	}

	/**
	 * @param transactionfee the transactionfee to set
	 */
	public void setTransactionfee(long transactionfee) {
		this.transactionfee = transactionfee;
	}

	/**
	 * @return the country
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * @param country the country to set
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	public String getProductform() {
		return productform;
	}

	public void setProductform(String productform) {
		this.productform = productform;
	}

	public String getFeessetting() {
		return feessetting;
	}

	public void setFeessetting(String feessetting) {
		this.feessetting = feessetting;
	}

	
	
	
	

}
